---
- name: split java_version into major/minor/patch components
  set_fact:
    split_version: "{{ java_version.split('.') }}"
- name: split redhat_java_version into major/minor/patch components
  set_fact:
    redhat_split_version: "{{ redhat_java_version.split('.') }}"
- name: ensure java variables are set
  set_fact:
    java_major_version: "{{ split_version[0] }}"
    zulu_major_minor_patch: "{{ split_version[0] }}.{{ split_version[1] }}+{{ split_version[2] }}"
    zulu_major_minor: "{{ split_version[0] }}.{{ split_version[1] }}"
    redhat_java_major_version: "{{ redhat_split_version[0] }}"
    redhat_zulu_major_minor_patch: "{{ redhat_split_version[0] }}.{{ redhat_split_version[1] }}+{{ redhat_split_version[2] }}"
    redhat_zulu_major_minor: "{{ redhat_split_version[0] }}.{{ redhat_split_version[1] }}"
- name: ensure java_zulu_version variable is set
  set_fact:
    java_zulu_version: "{{ split_version[2] | ternary('{{ zulu_major_minor_patch }}', '{{ zulu_major_minor }}') }}"
    redhat_java_zulu_version: "{{ redhat_split_version[2] | ternary('{{ redhat_zulu_major_minor_patch }}', '{{ redhat_zulu_major_minor }}') }}"
