- hosts: all
  remote_user: root
  become: true
  roles:
    - role: humio.java

    - role: AnsibleShipyard.ansible-zookeeper
      zookeeper_version: 3.4.14
      zookeeper_url: http://archive.apache.org/dist/zookeeper/zookeeper-{{zookeeper_version}}/zookeeper-{{zookeeper_version}}.tar.gz

    - role: humio.kafka
    
    - role: humio.server