- hosts: all
  remote_user: root
  become: true
  roles:
    - role: humio.java

    - role: AnsibleShipyard.ansible-zookeeper
      zookeeper_version: 3.6.2

    - role: humio.kafka
    
    - role: humio.server