galaxy_info:
  author: Martin Westergaard Lassen & Joel Watson
  description: Azul Zulu JDK for use with Humio
  company: Humio

  license: Apache

  min_ansible_version: 2.4

  platforms:
  - name: EL
    versions:
    - 7
  - name: Ubuntu
    versions:
    - xenial
    - bionic

  galaxy_tags:
  - java
  - humio

dependencies: []
